### ISSUE TITLE
Vanilla Build Error with Boilerplate

### ISSUE THREAD

**Issue by derrickeason** [vanilla/vanilla-cli#123]
Hinterland is building our Success Community theme and having some issues as described below:

The Team is trying to build the boilerplate. We have node, yarn, composer installed. But when we try to build it, it keeps giving this node_modules/natives error.

We have tried --reinitialize as well, still no luck. Any ideas? We have followed the doc

https://docs.vanillaforums.com/developer/theme-boilerplate/

https://docs.vanillaforums.com/developer/vanilla-cli/

192-168-1-122:success cindy$ ~/.composer/vendor/vanilla/vanilla-cli/bin/vanilla build --vanillasrc ~/Projects/vanilla/success/src --verbose

Checking dependencies for build process version vanilla/vanilla-cli

Skipping install for node process vanilla/vanilla-cli - Already installed

    Installed Version - 2.7.1

    Current Version - 2.7.1

/Users/cindy/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:137

    fn(nm.exports, cachingRequire, nm, nm.filename)

    ^

ReferenceError: internalBinding is not defined

    at fs.js:25:1

    at req_ (/Users/cindy/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:137:5)

    at Object.req [as require] (/Users/cindy/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:54:10)

    at Object.<anonymous> (/Users/cindy/.composer/vendor/vanilla/vanilla-cli/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)

    at Module._compile (internal/modules/cjs/loader.js:707:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)

    at Module.load (internal/modules/cjs/loader.js:605:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)

    at Function.Module._load (internal/modules/cjs/loader.js:536:3)

    at Module.require (internal/modules/cjs/loader.js:643:17)

**Comment by charrondev** [comment]
So there is a bit of data missing here:

- OS + version
- Node version
- Yarn version.

Native module issues generally come down to some combination of these things. 

My gut feeling is that they may be running Node 11 (which __just__ recently released). I seen reports of some similar errors.

I may update the dependencies here in the near future which _could_ fix this issue, but my general recommendation would be not to run the bleeding edge versions of node. Right now the tool has only been tested on Node 8 and node 10. Odd number versions of node do not have long term support from node itself so we do not support or test on those versions actively. See https://github.com/nodejs/Release.

**Comment by derrickeason** [comment]
Update from client:

> Thanks for the info. One of the machine has been downgrade to node10.10.0 via nvm. All working.

I'm going to close this ticket. Thanks for you help Adam!
