### ISSUE TITLE
Errors compiling TypeScript

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla-cli#128]
```
    throw new TSError(formatDiagnostics(configDiagnostics, cwd, ts, 0))
          ^
TSError: ⨯ Unable to compile TypeScript
A path in an 'extends' option must be relative or rooted, but '@vanilla/tsconfig/base.json' is not. (18001)
    at Object.register (/Users/stephanelafleche/Documents/vagrant-vanilla/vanilla-cli/node_modules/ts-node/src/index.ts:222:11)
    at Object.<anonymous> (/Users/stephanelafleche/Documents/vagrant-vanilla/vanilla-cli/node_modules/ts-node/src/bin.ts:103:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Running Vanilla Cli in Keystone returns the above error multiple times.

**Comment by charrondev** [comment]
Fixed in the latest version.
